import { MatchWithVenueCount, VenueWithMatchCount, Area, Genre } from '@/types'

export const areas: Area[] = [
  { id: '1', name: '渋谷', slug: 'shibuya', sort_order: 1 },
  { id: '2', name: '新宿', slug: 'shinjuku', sort_order: 2 },
  { id: '3', name: '銀座・有楽町', slug: 'ginza', sort_order: 3 },
  { id: '4', name: '六本木', slug: 'roppongi', sort_order: 4 },
  { id: '5', name: '秋葉原', slug: 'akihabara', sort_order: 5 },
]

export const genres: Genre[] = [
  { id: '1', name: 'スポーツバー', slug: 'sports-bar' },
  { id: '2', name: 'パブ', slug: 'pub' },
  { id: '3', name: '居酒屋', slug: 'izakaya' },
]

const now = Date.now()
const day = 24 * 60 * 60 * 1000

export const matches: MatchWithVenueCount[] = [
  {
    id: 'm1',
    competition_name: 'FIFA World Cup 2026',
    round: 'グループステージ',
    home_team: '日本',
    away_team: 'ドイツ',
    home_team_flag: '🇯🇵',
    away_team_flag: '🇩🇪',
    kickoff_at: new Date(now + 1 * day + 14 * 3600 * 1000).toISOString(),
    broadcast_channel: 'NHK BS',
    is_japan_national: true,
    venue_count: 8,
  },
  {
    id: 'm2',
    competition_name: 'FIFA World Cup 2026',
    round: 'グループステージ',
    home_team: 'ブラジル',
    away_team: 'アルゼンチン',
    home_team_flag: '🇧🇷',
    away_team_flag: '🇦🇷',
    kickoff_at: new Date(now + 1 * day + 18 * 3600 * 1000).toISOString(),
    broadcast_channel: 'DAZN',
    is_japan_national: false,
    venue_count: 6,
  },
  {
    id: 'm3',
    competition_name: 'FIFA World Cup 2026',
    round: 'グループステージ',
    home_team: '日本',
    away_team: 'スペイン',
    home_team_flag: '🇯🇵',
    away_team_flag: '🇪🇸',
    kickoff_at: new Date(now + 4 * day + 10 * 3600 * 1000).toISOString(),
    broadcast_channel: 'NHK総合',
    is_japan_national: true,
    venue_count: 9,
  },
  {
    id: 'm4',
    competition_name: 'FIFA World Cup 2026',
    round: 'グループステージ',
    home_team: 'フランス',
    away_team: 'イングランド',
    home_team_flag: '🇫🇷',
    away_team_flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    kickoff_at: new Date(now + 4 * day + 14 * 3600 * 1000).toISOString(),
    broadcast_channel: 'DAZN',
    is_japan_national: false,
    venue_count: 5,
  },
  {
    id: 'm5',
    competition_name: 'FIFA World Cup 2026',
    round: 'グループステージ',
    home_team: 'ポルトガル',
    away_team: 'モロッコ',
    home_team_flag: '🇵🇹',
    away_team_flag: '🇲🇦',
    kickoff_at: new Date(now + 5 * day + 9 * 3600 * 1000).toISOString(),
    broadcast_channel: 'DAZN',
    is_japan_national: false,
    venue_count: 4,
  },
  {
    id: 'm6',
    competition_name: 'FIFA World Cup 2026',
    round: 'グループステージ',
    home_team: '日本',
    away_team: 'コスタリカ',
    home_team_flag: '🇯🇵',
    away_team_flag: '🇨🇷',
    kickoff_at: new Date(now + 7 * day + 7 * 3600 * 1000).toISOString(),
    broadcast_channel: 'NHK BS',
    is_japan_national: true,
    venue_count: 10,
  },
  {
    id: 'm7',
    competition_name: 'FIFA World Cup 2026',
    round: 'グループステージ',
    home_team: 'ドイツ',
    away_team: 'スペイン',
    home_team_flag: '🇩🇪',
    away_team_flag: '🇪🇸',
    kickoff_at: new Date(now + 8 * day + 14 * 3600 * 1000).toISOString(),
    broadcast_channel: 'DAZN',
    is_japan_national: false,
    venue_count: 5,
  },
  {
    id: 'm8',
    competition_name: 'FIFA World Cup 2026',
    round: 'ラウンド16',
    home_team: 'ブラジル',
    away_team: 'フランス',
    home_team_flag: '🇧🇷',
    away_team_flag: '🇫🇷',
    kickoff_at: new Date(now + 14 * day + 18 * 3600 * 1000).toISOString(),
    broadcast_channel: 'DAZN',
    is_japan_national: false,
    venue_count: 7,
  },
  {
    id: 'm9',
    competition_name: 'FIFA World Cup 2026',
    round: '準々決勝',
    home_team: '日本',
    away_team: 'ポルトガル',
    home_team_flag: '🇯🇵',
    away_team_flag: '🇵🇹',
    kickoff_at: new Date(now + 20 * day + 14 * 3600 * 1000).toISOString(),
    broadcast_channel: 'NHK総合',
    is_japan_national: true,
    venue_count: 10,
  },
  {
    id: 'm10',
    competition_name: 'FIFA World Cup 2026',
    round: '決勝',
    home_team: 'ブラジル',
    away_team: 'アルゼンチン',
    home_team_flag: '🇧🇷',
    away_team_flag: '🇦🇷',
    kickoff_at: new Date(now + 30 * day + 18 * 3600 * 1000).toISOString(),
    broadcast_channel: 'NHK総合',
    is_japan_national: false,
    venue_count: 8,
  },
]

export const venues: VenueWithMatchCount[] = [
  {
    id: 'v1',
    name: 'SHIBUYA SPORTS BAR GOAL',
    address: '東京都渋谷区道玄坂1-2-3',
    nearest_station: '渋谷駅 徒歩5分',
    image_url: 'https://images.unsplash.com/photo-1543269664-56d93c1b41a6?w=800',
    official_site_url: 'https://example.com',
    reservation_url: 'https://example.com/reserve',
    is_reservation_available: true,
    is_featured: true,
    description: '渋谷最大級のスポーツバー。全30台のスクリーンでワールドカップを全試合放映。',
    area: areas[0],
    genre: genres[0],
    match_count: 8,
  },
  {
    id: 'v2',
    name: 'SHIBUYA PUB OFFSIDE',
    address: '東京都渋谷区渋谷2-5-8',
    nearest_station: '渋谷駅 徒歩7分',
    image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800',
    official_site_url: 'https://example.com',
    reservation_url: null,
    is_reservation_available: false,
    is_featured: false,
    description: '英国スタイルのパブ。本場のギネスを飲みながらサッカー観戦。',
    area: areas[0],
    genre: genres[1],
    match_count: 5,
  },
  {
    id: 'v3',
    name: '新宿スポーツバー EXTRA TIME',
    address: '東京都新宿区歌舞伎町1-3-5',
    nearest_station: '新宿駅 徒歩8分',
    image_url: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800',
    official_site_url: 'https://example.com',
    reservation_url: 'https://example.com/reserve',
    is_reservation_available: true,
    is_featured: true,
    description: '新宿歌舞伎町のスポーツバー。深夜試合も朝まで営業。',
    area: areas[1],
    genre: genres[0],
    match_count: 7,
  },
  {
    id: 'v4',
    name: '新宿居酒屋 ワールド',
    address: '東京都新宿区西新宿2-1-4',
    nearest_station: '新宿駅 徒歩3分',
    image_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    official_site_url: 'https://example.com',
    reservation_url: 'https://example.com/reserve',
    is_reservation_available: true,
    is_featured: false,
    description: '和食を楽しみながらワールドカップ観戦。団体予約歓迎。',
    area: areas[1],
    genre: genres[2],
    match_count: 4,
  },
  {
    id: 'v5',
    name: 'GINZA SPORTS LOUNGE',
    address: '東京都中央区銀座6-10-1',
    nearest_station: '銀座駅 徒歩2分',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    official_site_url: 'https://example.com',
    reservation_url: 'https://example.com/reserve',
    is_reservation_available: true,
    is_featured: true,
    description: '銀座の高級スポーツラウンジ。4K大型スクリーン完備。',
    area: areas[2],
    genre: genres[0],
    match_count: 6,
  },
  {
    id: 'v6',
    name: '有楽町パブ THE KICK OFF',
    address: '東京都千代田区有楽町2-9-18',
    nearest_station: '有楽町駅 徒歩1分',
    image_url: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800',
    official_site_url: 'https://example.com',
    reservation_url: null,
    is_reservation_available: false,
    is_featured: false,
    description: '有楽町駅すぐのアイルランドパブ。試合中は店内が一体となって応援。',
    area: areas[2],
    genre: genres[1],
    match_count: 3,
  },
  {
    id: 'v7',
    name: '六本木スポーツバー OVERTIME',
    address: '東京都港区六本木6-1-2',
    nearest_station: '六本木駅 徒歩4分',
    image_url: 'https://images.unsplash.com/photo-1596463059283-da257325bab8?w=800',
    official_site_url: 'https://example.com',
    reservation_url: 'https://example.com/reserve',
    is_reservation_available: true,
    is_featured: true,
    description: '六本木の国際的スポーツバー。英語・日本語スタッフ在籍。外国人サポーターも多数来店。',
    area: areas[3],
    genre: genres[0],
    match_count: 9,
  },
  {
    id: 'v8',
    name: 'ROPPONGI PUB PENALTY',
    address: '東京都港区六本木7-8-3',
    nearest_station: '六本木駅 徒歩6分',
    image_url: 'https://images.unsplash.com/photo-1525268323446-0505b6fe7778?w=800',
    official_site_url: 'https://example.com',
    reservation_url: null,
    is_reservation_available: false,
    is_featured: false,
    description: '六本木のアットホームなパブ。毎試合パブリックビューイング開催。',
    area: areas[3],
    genre: genres[1],
    match_count: 4,
  },
  {
    id: 'v9',
    name: '秋葉原スポーツバー MATCH DAY',
    address: '東京都千代田区外神田3-2-1',
    nearest_station: '秋葉原駅 徒歩5分',
    image_url: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800',
    official_site_url: 'https://example.com',
    reservation_url: 'https://example.com/reserve',
    is_reservation_available: true,
    is_featured: false,
    description: '秋葉原エリアのスポーツバー。ゲーマーとサッカーファンが集まる独自の空間。',
    area: areas[4],
    genre: genres[0],
    match_count: 5,
  },
  {
    id: 'v10',
    name: '秋葉原居酒屋 フットボール',
    address: '東京都千代田区外神田5-3-9',
    nearest_station: '秋葉原駅 徒歩7分',
    image_url: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800',
    official_site_url: 'https://example.com',
    reservation_url: 'https://example.com/reserve',
    is_reservation_available: true,
    is_featured: false,
    description: '秋葉原の気軽に入れる居酒屋。大型モニターで全試合対応。',
    area: areas[4],
    genre: genres[2],
    match_count: 3,
  },
]

// 店舗×試合の紐付け
export const venueMatches: { venueId: string; matchId: string }[] = [
  { venueId: 'v1', matchId: 'm1' },
  { venueId: 'v1', matchId: 'm3' },
  { venueId: 'v1', matchId: 'm6' },
  { venueId: 'v2', matchId: 'm1' },
  { venueId: 'v2', matchId: 'm2' },
  { venueId: 'v3', matchId: 'm1' },
  { venueId: 'v3', matchId: 'm3' },
  { venueId: 'v3', matchId: 'm6' },
  { venueId: 'v3', matchId: 'm9' },
  { venueId: 'v4', matchId: 'm1' },
  { venueId: 'v4', matchId: 'm6' },
  { venueId: 'v5', matchId: 'm2' },
  { venueId: 'v5', matchId: 'm4' },
  { venueId: 'v5', matchId: 'm8' },
  { venueId: 'v6', matchId: 'm3' },
  { venueId: 'v7', matchId: 'm1' },
  { venueId: 'v7', matchId: 'm3' },
  { venueId: 'v7', matchId: 'm6' },
  { venueId: 'v8', matchId: 'm2' },
  { venueId: 'v9', matchId: 'm1' },
]

export function getVenuesForMatch(matchId: string): VenueWithMatchCount[] {
  const venueIds = venueMatches
    .filter((vm) => vm.matchId === matchId)
    .map((vm) => vm.venueId)
  return venues.filter((v) => venueIds.includes(v.id))
}

export function getMatchesForVenue(venueId: string): MatchWithVenueCount[] {
  const matchIds = venueMatches
    .filter((vm) => vm.venueId === venueId)
    .map((vm) => vm.matchId)
  return matches.filter((m) => matchIds.includes(m.id))
}

export function getUpcomingMatches(): MatchWithVenueCount[] {
  const now = new Date()
  const weekLater = new Date(Date.now() + 7 * day)
  return matches
    .filter((m) => new Date(m.kickoff_at) >= now && new Date(m.kickoff_at) <= weekLater)
    .slice(0, 6)
}

export function getFeaturedVenues(): VenueWithMatchCount[] {
  return venues.filter((v) => v.is_featured)
}
